### ISSUE TITLE
Make client specific to domain when getting workflows

### ISSUE THREAD

**Issue by lukamacun-ts** [uber-go/cadence-client#1041]
One of the parameters for building workflow client is `domainName` but it's used only for signaling and starting workflows, but when trying to get workflow just by `workflow_id ` client returns workflow with that id from whichever domain it finds. 

**Proposed Solution**
Make all operations on workflows client domain specific

**Comment by ibarrajo** [comment]
One of the reasons why you would get results from multiple domains is because in a multi-regional deployment of cadence, if you use a global domain, domain history is replicated across the regions. Essentially you have two domains that share the same name and one is set as the active and the other as the passive.
