### ISSUE TITLE
sleep facility for activities

### ISSUE THREAD

**Issue by yiminc-zz** [uber-go/cadence-client#153]
We need a sleep API that would sleep on real clock in normal case, but sleep on mock clock in unit test environment, something like:
cadence.ActivitySleep(ctx context.Context, d time.Duration)
then, in activity code, instead of:
time.Sleep(d)
it should do:
cadence.ActivitySleep(ctx, d)
this way, ActivitySleep would sleep on real clock in normal case, but sleep on mock clock on unit tests.

**Comment by ibarrajo** [comment]
Closing this since we do have sleep within workflows.

https://pkg.go.dev/go.uber.org/cadence/workflow#Sleep

Activities on the other hand, depending on the type of testing, the time module could be stubbed out for testing.
https://stackoverflow.com/questions/18970265/is-there-an-easy-way-to-stub-out-time-now-globally-during-test
