### ISSUE TITLE
need a way to run workflow for a given history locally

### ISSUE THREAD

**Issue by yiminc** [uber-go/cadence-client#274]
make it possible to debug in IDE (to step through) for a given history.

would be great if we could run a saved history from a file (with json formatted history), so people can change history to test different kind of scenario. 

this will make it possible to unit test the replay part of the code

**Comment by mfateev** [comment]
One option is to use worker query per https://github.com/uber/cadence/issues/390

**Comment by Groxx** [comment]
yay, already an open issue!
this would be super useful for us, both for offline validation of changes (make sure we don't introduce breaking changes before we deploy) and for inspecting historical workflows in bulk (since we could just write a query handler for what we want to know, and run queries on a ton of old workflows).  count me in as a +1 for this feature.

**Comment by mfateev** [comment]
https://github.com/uber-go/cadence-client/pull/441
The only missing feature is an ability to replay from a history downloaded from UI or CLI.
