### ISSUE TITLE
Support RecordActivityHeartbeat by ID

### ISSUE THREAD

**Issue by vancexu** [uber-go/cadence-client#296]
Since we provide both CompleteActivity and CompleteActivityByID, 
we might also want to provide RecordActivityHeartbeatByID

**Comment by ryanwalls** [comment]
@samarabbas We are implementing our cutover to cadence and it would be nice to heartbeat by workflow id/activity id instead of token.  How feasible would it be to do this?

**Comment by samarabbas** [comment]
@ryanwalls implementing this feature should be pretty straightforward, considering CompleteActivityById is already supported by both server and client.  Here is the PR: https://github.com/uber/cadence/pull/434.
RecordActivityHeartbeatByID is slightly lower priority for us as most of the time heartbeat is done by the same process which picked up the activity so it already has access to tasktoken.  But this is definitely on our radar.  
What is your use case of heartbeating using ID instead of tasktoken?

**Comment by ryanwalls** [comment]
@samarabbas We are hiding what type of workflow engine is being used (SWF vs Cadence) from our activity workers.  They simply call a rest API `/workflows/<workflow id>/activities/<activity id>` to update their status.  It's just more convenient/restful to use `workflow id` and `activity id` in our rest endpoints.

**Comment by samarabbas** [comment]
Makes sense.  Just a heads up, this feature of complete/fail/cancel/heartbeat activities is only supported by Cadence.  I don't think SWF has support for this.

**Comment by ryanwalls** [comment]
@samarabbas Where do we get `domainID` as `CompleteActivityByID` requires it?  

It doesn't seem to be available using the `DomainClient`?
https://github.com/uber-go/cadence-client/blob/e7123e7586e43a82c0a658403523f890d14668a9/internal/client.go#L254-L279

p.s.
We are using a project https://github.com/sclasen/swfsm that stores activity id for SWF.  So we can get it for SWF.

**Comment by samarabbas** [comment]
@ryanwalls looks like we incorrectly exposed the domainID on this API instead of domainName.  DomainID is a unique identifier created within the Cadence server to identify domains, but it should not be leaked to Cadence clients.  Cadence client should always use the registered domainName to identify the domain.
I have filed a bug on Cadence server to fix this: https://github.com/uber/cadence/issues/515
