### ISSUE TITLE
cancel context does not close channel

### ISSUE THREAD

**Issue by yiminc-zz** [uber-go/cadence-client#481]
In below test code, when the context is canceled, we should close the channel so that selector.Select() would return immediately. 

However, it is not clear what is the desired behavior for selector when the context is closed. The Select() method does not return error, and the contract is that when Select() returns, at least one case that selector is waiting for should be true.

```
func TestCancelContext(t *testing.T) {
	workflowFn := func(ctx workflow.Context) (bool, error) {
		cctx, cancel := workflow.WithCancel(ctx)
		c := workflow.GetSignalChannel(cctx, "sig-name")
		s := workflow.NewSelector(cctx)
		var called bool
		s.AddReceive(c, func(c workflow.Channel, more bool) {
			c.Receive(cctx, nil)
			called = true
		})
		cancel()
		s.Select(cctx)
		return called, nil
	}

	testSuite := &testsuite.WorkflowTestSuite{}
	env := testSuite.NewTestWorkflowEnvironment()
	env.RegisterDelayedCallback(func() {
		env.SignalWorkflow("sig-name", nil)
	}, 100*time.Millisecond)

	workflow.Register(workflowFn)
	env.ExecuteWorkflow(workflowFn)

	var result bool
	env.GetWorkflowResult(&result)
	assert.False(t, result) // fails!  it's actually true.
}
```

**Comment by Groxx** [comment]
For additional context: currently canceling a context does very little, *except* that ExecuteActivity returns with a canceled error (and does not actually exec), and I assume local activities / child workflows do the same.

That was kinda surprising to me.  I'm not totally sure what the ideal behavior would be, but it probably deserves good docs warning about it (on `workflow.WithCancel`) or perhaps everything could "abort" if operating on a canceled context.  (Selectors being the major complicator since they don't return an error currently)

---

Selectors can deal with this in a nicely Go-like way by tossing `ctx.Done()` into the mix:
```
s.AddReceive(ctx.Done(), func(c workflow.Channel, more bool) {
  // deliberately empty.  func arg can't be nil though - maybe that could be allowed?
})
```
and otherwise, it kinda feels like maybe this is all correct / expected-if-you-think-about-it behavior?  Goroutines can't be canceled, nor can (blocking) selects or channel sends / receives.  Still, given all the context passing I was kinda expecting it to work as a cancel-all-the-things func, and it's definitely not one.
