### ISSUE TITLE
Add activity heartbeat metric

### ISSUE THREAD

**Issue by mfateev** [uber-go/cadence-client#520]
Currently there is no metric emitted related to activity heartbeat. So customers have no way to monitor it.

**Comment by szimmer1** [comment]
For example, we want to trigger an alert if a long-running activity has been inactive. We have our own metrics on the workflow level, but umonitor constrains the sustain to <120mins. An activity may take longer. Since we want to avoid false-positives, it would be better to trigger an alert with a query based on an intra-activity metric (e.g. heartbeat).

Like @mfateev said we could implement our own metric but a cadence-side solution may be re-used by other cadence users

**Comment by mfateev** [comment]
@szimmer1  For "long running activity being inactive" you can use activity timeout metric

**Comment by vancexu** [comment]
In latest v0.7.1, there are metrics about RecordActivityTaskHeartbeat. 
Cadence will emit request count, invalid request count, err count, and latency for every service API call, including RecordActivityTaskHeartbeat from v0.7.1
